// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCI9ScmA3JSGbQnGZcKNrLyoggHPMrS2A0",
      authDomain: "dreamcast-event-app-2024-2nd.firebaseapp.com",
      databaseURL: "https://dreamcast-event-app-2024-2nd-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "dreamcast-event-app-2024-2nd",
      storageBucket: "dreamcast-event-app-2024-2nd.appspot.com",
      messagingSenderId: "642452475161",
      appId: "1:642452475161:web:919e1eaf1bde8359824988",
      measurementId: "G-16K38M4J8N"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyDJ1f5zM-_YQTAom0GRb1sO4beBZJyxsm8",
      authDomain: "dreamcast-event-app-2024-2nd.firebaseapp.com",
      databaseURL: "https://dreamcast-event-app-2024-2nd-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "dreamcast-event-app-2024-2nd",
      storageBucket: "dreamcast-event-app-2024-2nd.appspot.com",
      messagingSenderId: "642452475161",
      appId: "1:642452475161:android:d8667809c74b549e824988",
      measurementId: "G-16K38M4J8N"
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyBplhouC5pGqSdepYWUyMIgFYyEwxqSJ_U",
      authDomain: "dreamcast-event-app-2024-2nd.firebaseapp.com",
      databaseURL: "https://dreamcast-event-app-2024-2nd-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "dreamcast-event-app-2024-2nd",
      storageBucket: "dreamcast-event-app-2024-2nd.appspot.com",
      messagingSenderId: "642452475161",
      appId: "1:642452475161:ios:00edd353fd9424c5824988",
      measurementId: "G-16K38M4J8N"
  );

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyCI9ScmA3JSGbQnGZcKNrLyoggHPMrS2A0",
      authDomain: "dreamcast-event-app-2024-2nd.firebaseapp.com",
      databaseURL: "https://dreamcast-event-app-2024-2nd-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "dreamcast-event-app-2024-2nd",
      storageBucket: "dreamcast-event-app-2024-2nd.appspot.com",
      messagingSenderId: "642452475161",
      appId: "1:642452475161:web:919e1eaf1bde8359824988",
      measurementId: "G-16K38M4J8N"
  );
}